### ISSUE TITLE
raw button does not give raw link, it downloads file to local drive, whicha ctually should be the case with download button and not raw button

### ISSUE THREAD

**Issue by vdhumaskar-cci** [darshilparmar/tokyo-olympic-azure-data-engineering-project#5]
raw button does not give raw link, it downloads file to local drive, whicha ctually should be the case with download button and not raw button
Also if manually type the raw link from youtube to linked service, its test connection fails to preview data

**Comment by vdhumaskar-cci** [comment]
Please guide me how to succesfully set a linkedservice using raw ink?

**Comment by JasonBorstal** [comment]
same here cannot get url so preview data does not work.

**Comment by KumarAyush007** [comment]
Same here , unable to get the raw data link
It start downloading in local drive

**Comment by darshilparmar** [comment]
Just right click on RAW button and copy the link address - https://github.com/darshilparmar/tokyo-olympic-azure-data-engineering-project/raw/main/data/Athletes.csv
